#!/system/bin/sh
# main runner (process manager) for barnacle, root required

: ${brncl_path:=.}

export brncl_path
echo "Killing " `cat ${brncl_olsrd_pid_file}`
kill -15 `cat ${brncl_olsrd_pid_file}`
