#!/system/bin/sh
# main runner (process manager) for barnacle, root required

: ${brncl_path:=.}

export brncl_path
pid=`cat ${brncl_olsrd_pid_file}`
if [ $pid -ne '0' ]; then
	echo "Killing " $pid
	kill -15 $pid
fi
