#!/system/bin/sh
# main runner (process manager) for olsrd, root required

# log environment for debugging
set > $brncl_path/../app_log/environment.log 2>&1

# zero out debug log so it doesn't get huge
echo "" > $brncl_path/../app_log/olsrd.log 2>&1


cd $brncl_path

# run olsrd
echo pwd: `pwd`
./olsrd -f "${olsrd_conf_path}" -i $brncl_if_lan > $brncl_path/../app_log/olsrd.log 2>&1
# echo `ps | ./grep '[o]lsrd' | ./awk '{print $2;}'` > $brncl_path/../app_log/olsrd.pid